include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - build/**

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
